- build.gradle
- src/main/java/grep/neogul_coder/NeogulCoderApplication.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostSaveRequest.java
- src/main/java/grep/neogul_coder/domain/review/Review.java
- src/main/java/grep/neogul_coder/domain/review/tag/ReviewMessage.java
- src/main/java/grep/neogul_coder/domain/review/tag/ReviewTag.java
- src/main/java/grep/neogul_coder/domain/review/tag/ReviewTagging.java
- src/main/java/grep/neogul_coder/domain/review/tag/ReviewType.java
- src/main/java/grep/neogul_coder/global/response/ApiResponse.java
- src/main/java/grep/neogul_coder/test/Test.java
- 이후 PR 작성
---
- 공통 응답 객체 ApiResponse 작성
- 스터디 모집 글, 리뷰 엔티티 작성
- 스터디 모집글 저장 swagger 작성
---
- 필드: HttpStatus, code, message, data 
- 정적 팩토리 메서드를 통한 생성 방법 제공
---
> [EA3-81] feature: 스터디 모집 글, 리뷰 엔티티 작성

- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
- src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
- src/main/java/grep/neogul_coder/global/response/ApiResponse.java
ApiResponse에서 conflict 해결 이후 발생하는 문제 일부 수정했고 구조도 약간 변경
앞으로 필요한 응답이 있다면 자유롭게 커스텀해서 사용하시면 될 듯 합니다.
> refactor:ApiResponse 변경

- src/main/java/grep/neogul_coder/domain/attendance/Attendance.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceController.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceSpecification.java
- 이후 PR 작성
- 출석 엔티티 작성
- 출석 컨트롤러 생성
> [EA3-98] feature: 출석 엔티티 작성

- src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentPostStatus.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostEditRequest.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostSaveRequest.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostStatusEditRequest.java
- src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
- src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
- src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
- src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewPagingContentsInfo.java
Closes #17 
- 리뷰( 주관글 ) 페이징 조회 추가
- 리뷰 API, 모집글 API URI 정리
- 모집글 모집 상태, 모집 마감일 추가
- 모집글 모집 상태 변경 API 추가
---
> [EA3-81] feature: 모집글 상태, 마감일 추가 및 리뷰 주관글 API 명세서 추가

- src/main/java/grep/neogul_coder/domain/calender/entity/PersonalCalender.java
- src/main/java/grep/neogul_coder/domain/calender/entity/TeamCalender.java
#33 
각 일정에 대한 softdelete 추가 했습니다
> [EA3-74] feature : 엔티티 추가

- src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatSwaggerController.java
- src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/GroupChatSwaggerRequest.java
- src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/GroupChatSwaggerResponse.java
#9 
가독성을 위해 dto @Getter와 @Builder 를 붙여서 리팩토링 후 컨트롤러도 이를 반영해 수정하였습니다
> [EA3-73] feature : 그룹채팅 스웨거 builder로 리팩토링

- src/main/java/grep/neogul_coder/domain/attendance/Attendance.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceController.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceSpecification.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/dto/response/AttendanceResponse.java
Closes #27  
출석 스웨거 작성
- 출석 조회
- 출석 체크
> [EA3-97] feature: 출석 스웨거 작성

- .github/workflows/create-jira-issue.yml
브랜치 자동 생성시 develop 기준으로 생성되도록 변경했습니다.
> [EA3-44] chore: 브랜치 생성 경로 변경

- src/main/java/grep/neogul_coder/domain/quiz/controller/QuizController.java
- src/main/java/grep/neogul_coder/domain/quiz/controller/QuizSpecification.java
- src/main/java/grep/neogul_coder/domain/quiz/controller/dto/request/QuizRequest.java
- src/main/java/grep/neogul_coder/domain/quiz/controller/dto/response/QuizResponse.java
- src/main/java/grep/neogul_coder/domain/quiz/entity/Quiz.java
Closes #53 
AI Quiz swagger 작성했습니다.
AI Quiz 게시글 id , 게시글 카테고리, 게시글 내용 받아서 퀴즈와 ture/false로 반환하도록 했습니다.
request에 Null값 들어오지 않게 변경했습니다.
Controller 구현체로 변경하였습니다.
----------------
> [EA3-109] feature:Quiz swagger 작성

- src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyResponse.java
Closes #13 
엔드포인트 변경 및 Response 필드 추가
- 스터디 관리 엔드포인트 경로를 수정
- StudyResponse에 진행 일수, 출석, 달력, 게시글 필드 추가
> [EA3-77] refactor: 엔드포인트 변경 및 Response 필드 추가

- src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
- src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteSpecification.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkCreateRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkDeleteRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteCreateRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteDeleteRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVotePeriodResponse.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteResponse.java
- src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteStatResponse.java
- src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVote.java
- src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVotePeriod.java
- src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVoteStat.java
Closes #16 
스터디 최적 시간 투표 관련 엔티티 및 스웨거 작성
- 투표 기간 설정
- 투표 단건/다건 제출
- 투표 단건/다건 수정
- 투표 단건/다건/전체 삭제
- 투표 통계
상세한 사진을 모두 넣기엔 너무 길어져서 상세한 사진은 첨부하지 않았습니다ㅠㅠ
> [EA3-80] feature: 스터디 최적 시간 투표 관련 엔티티 및 스웨거 작성

- src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
- src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
- src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
- src/main/java/grep/neogul_coder/domain/review/controller/service/ReviewService.java
- src/main/java/grep/neogul_coder/domain/review/controller/service/request/ReviewSaveServiceRequest.java
- src/main/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepository.java
- src/main/java/grep/neogul_coder/domain/review/repository/ReviewRepository.java
- src/main/java/grep/neogul_coder/domain/study/Study.java
- src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
- src/main/java/grep/neogul_coder/domain/users/repository/UserRepository.java
References #66 
- 리뷰 대상 조회 
- 리뷰 생성
- 스터디 맴버 중 본인을 제외한 맴버의 이름들을 반환
---
- ReviewTagFinder : String 값 리뷰 태그를 입력 받아 일치 하는 리뷰 태그를 찾는 역할
- ReviewTags : 찾은 태그들이 하나의 리뷰 타입( 좋아요, 아쉬워요 )인지 확인
- Review 생성시 MyReviewTag 들도 같이 저장
- 외부에서는 Review를 저장 한다는 것만 알면 된다고 생각 하기 때문에 따로 MyReviewTag 외부 노출X
> [EA3-118] Feature: 리뷰 대상 조회 및 생성 구현

- src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
- src/main/java/grep/neogul_coder/domain/review/ReviewTags.java
- src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTargetUsersInfo.java
- src/main/java/grep/neogul_coder/domain/review/controller/service/ReviewService.java
- src/main/java/grep/neogul_coder/domain/study/Study.java
- src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
- src/test/java/grep/neogul_coder/domain/review/ReviewTagsTest.java
References #66 
- 리뷰 대상 조회시 스터디 이름, 스터디 이미지 URL 추가
- 리뷰 조회, 저장 코드 리팩토링
- getTargetUserInfos To findReviewTargetUsers 
- 어떤 타겟인지 모호 하다고 생각 하여 리뷰 타겟으로 이름 변경
---
- getReviewType To ensureSingleReviewType
- 하나의 리뷰 타입을 보장 한다는 것을 명시
> [EA3-118] Feature: 리뷰 대상 조회시 스터디 이름, 이미지 추가 및 코드 리팩토링

- src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVote.java
- src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVotePeriod.java
- src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVoteStat.java
References #92 
최적 시간 투표 관련 엔티티 GenerationType.AUTO에서 IDENTITY로 변경
> [EA3-134] refactor : 최적 시간 투표 관련 엔티티 GenerationType.IDENTITY로 변경

- src/main/java/grep/neogul_coder/domain/comment/Comment.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
- src/main/java/grep/neogul_coder/domain/studypost/StudyPost.java
References #86 
- 모집글 삭제 상태 제거 및 EnumType.String 추가
> [EA3-132] Feature: 모집글 삭제 상태 제거및 EnumType 추가

- src/main/java/grep/neogul_coder/global/config/security/SecurityConfig.java
h2-console접근을 위해 headers.disable() 추가
> [EA3] refactor : h2-console 접근 위해 headers.disable() 추가

- src/main/resources/import.sql
> [EA3] chore : 목업데이터 파일 추가

- src/main/java/grep/neogul_coder/global/entity/BaseEntity.java
> [EA3-132] feature: baseEntity getter 중복 제거

- src/main/java/grep/neogul_coder/domain/quiz/entity/Quiz.java
- src/main/java/grep/neogul_coder/global/entity/BaseEntity.java
develop 브랜치의 최신 기능 및 수정 사항을 main 브랜치로 반영하여 배포
> [EA3] chore: develop → main 브랜치 머지

- src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
- src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
- src/main/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepository.java
- src/main/java/grep/neogul_coder/domain/review/repository/ReviewRepository.java
- src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
- src/main/java/grep/neogul_coder/global/init/ReviewTagInitializer.java
- 리뷰 생성시 스터디 조회후 생성
- 리뷰 생성시 request 기본 생성자 적용
- 리뷰 생성시 이미 작성한 리뷰인지 예외 추가
> [EA3-132] feature: 리뷰 기능 예외 추가 및 수정

- src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/LinkUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/PrUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/prtemplate/repository/LinkRepository.java
- src/main/java/grep/neogul_coder/domain/prtemplate/service/LinkService.java
- src/main/java/grep/neogul_coder/domain/prtemplate/service/PrTemplateService.java
- src/main/resources/import.sql
Closes #104 
조회와 수정에서 500error 와 400error 발생하여 수정
조회에서 리뷰에 최신 5개만 꺼내와서 조회하도록 만들어두어서 review sql문에 creatDate 추가
수정 시점에 기존 url은 activated = false로 수정
조회에 activated = true만 조회하도록 변경
> [EA3-136] Fix: PR 템플릿 에러 수정

- src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
> [EA3-133] fix: 에러코드 오류 수정

- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostDetailsInfo.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/save/JoinedStudyLoadInfo.java
- src/main/java/grep/neogul_coder/domain/study/Study.java
- src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
- src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementSpecification.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/request/ExtendStudyRequest.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/response/ExtendParticipationResponse.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyExtensionResponse.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyInfoResponse.java
- src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
- src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepository.java
- src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
- src/main/java/grep/neogul_coder/domain/study/service/StudyManagementService.java
References #89 
스터디 관리 조회 기능 추가
- 스터디 연장 여부 조회
- 연장 스터디 참여 멤버 목록 조회
- study 필드 LocalDate -> LocalDateTime 변경
> [EA3-133] feature: 스터디 관리 조회 기능 추가

- src/main/java/grep/neogul_coder/domain/calender/repository/PersonalCalendarQueryRepository.java
- src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarQueryRepository.java
- src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
#55 
일정을 삭제 후 날짜별 조회에서는 그대로 조회 되어서 QueryDSL 부문에 activated = true 조건 추가하였습니다
> [EA3-112] feature : 날짜별 조회 쿼리 수정

- src/main/java/grep/neogul_coder/domain/attendance/Attendance.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceController.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceSpecification.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/dto/response/AttendanceInfoResponse.java
- src/main/java/grep/neogul_coder/domain/attendance/controller/dto/response/AttendanceResponse.java
- src/main/java/grep/neogul_coder/domain/attendance/exception/code/AttendanceErrorCode.java
- src/main/java/grep/neogul_coder/domain/attendance/repository/AttendanceRepository.java
- src/main/java/grep/neogul_coder/domain/attendance/service/AttendanceService.java
- src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
- src/test/java/grep/neogul_coder/domain/attendance/service/AttendanceServiceTest.java
Closes #152 
feature: 출석 기능 및 테스트
- 출석 조회 기능
- 출석 체크 기능
- 테스트 작성
**출석률**
- studyMember 생성일이 스터디 시작일보다 빠르면 스터디 시작일부터 스터디 종료일까지
- studyMember 생성일이 스터디 시작일보다 느리면 생성일부터 스터디 종료일까지
**테스트 결과**
> [EA3-162] feature: 출석 기능 및 테스트

- src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentErrorCode.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/RecruitmentPostComment.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/RecruitmentPostCommentController.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/RecruitmentPostCommentSpecification.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentSaveRequest.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
- src/main/java/grep/neogul_coder/domain/recruitment/comment/service/RecruitmentPostCommentService.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostUpdateRequest.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
- src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostUpdateServiceRequest.java
References #86 
- 모집글 수정시 모집 마감기간 추가
- 모집글 댓글 생성, 수정, 삭제 추가
> [EA3-138] feature: 모집글 수정시 모집 마감 기간 추가

- src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
References #92 
- service가 아직 수정이 되어있지 않아 반영이 안되어있는데 controller에 함께 올라가 있어서 service를 지웠습니당..!
> [EA3-134] chore: 스터디 모임시간 조율 - service 제외

- src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
Closes #151 
스터디 생성, 수정 이미지 업로드 환경 분기 처리 수정
> [EA3-161] refactor: 스터디 생성, 수정 이미지 업로드 환경 분기 처리 수정

- src/main/java/grep/neogul_coder/domain/studyapplication/controller/ApplicationController.java
- src/main/java/grep/neogul_coder/domain/studyapplication/controller/ApplicationSpecification.java
- src/main/java/grep/neogul_coder/domain/studyapplication/controller/dto/response/MyApplicationPagingResponse.java
- src/main/java/grep/neogul_coder/domain/studyapplication/repository/ApplicationQueryRepository.java
- src/main/java/grep/neogul_coder/domain/studyapplication/service/ApplicationService.java
References #165 
스터디 신청 목록 페이지네이션 및 필터링
- 스터디 신청 목록 조회 페이지네이션
- 스터디 신청 목록 조회 신청 상태 필터링
> [EA3-168] feature: 스터디 신청 목록 페이지네이션 및 필터링

- src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
- src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
- src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyUpdateRequest.java
Closes #151 
스터디 생성, 수정 request imageUrl 필드 삭제
> [EA3-161] refactor: 스터디 생성, 수정 request imageUrl 필드 삭제

- src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
- src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyResponse.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
- src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/FreePostInfo.java
- src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
- src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostRepository.java
> [EA3-167] feature: 스터디 조회 기능 구현

- src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationPagingResponse.java
- src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationResponse.java
- src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
References#165 
모집글 신청 목록 조회 이미지 필드 추가 및 쿼리 수정
- ReceivedApplicationResponse profileImageUrl 필드 추가
- 모집글 신청 목록 조회 시 APPLYING 상태만 조회
> [EA3-168] refactor: 모집글 신청 목록 조회 이미지 필드 추가 및 쿼리 수정

- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
- src/main/java/grep/neogulcoder/domain/alram/entity/Alarm.java
- src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
- src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
- src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
- src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
- src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
- src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
- src/main/java/grep/neogulcoder/domain/users/controller/UserSpecification.java
- src/main/java/grep/neogulcoder/domain/users/controller/dto/response/AllUserResponse.java
- src/main/java/grep/neogulcoder/domain/users/repository/UserRepository.java
- src/main/java/grep/neogulcoder/domain/users/service/UserService.java
- src/main/java/grep/neogulcoder/global/provider/InviteMessageProvider.java
- src/main/java/grep/neogulcoder/global/provider/MessageProvidable.java
- src/main/java/grep/neogulcoder/global/provider/finder/MessageFinder.java
References #204 
MessageFinder를 통해 알람 보낼 메시지 설정 가능하도록 구현
알람 생성, 조회, 읽음 처리 하는 로직 구현
MessageFinder를 통해서 메시지를 각자 구현체를 만들어 작성 가능하도록 변경
알람 생성 및 조회, 전체 읽음처리 로직 구현(차후 스터디 초대는 제외할 예정)
> [EA3-178]Feature: 알람 및 알람 메시지 인프라 구현

- src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
누락된 알림 타입 TIME_VOTE_REQUEST을 추가했습니다.
> [EA3-134] fix : 누락된 알림 타입 추가

- src/main/java/grep/neogulcoder/domain/studypost/controller/dto/request/StudyPostUpdateRequest.java
- src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/CommentInfo.java
Closes #153 
- 스터디 게시글 업데이트 오류 수정
- 스터디 게시글 댓글ID 필드명 변경
- enumType NotBlank 어노테이션 적용으로 인한 오류 수정
- 스터디 게시글 댓글 식별자 필드명 ID To commentId 변경
> [EA3-163] Fix: 스터디 게시글 업데이트 오류 수정

- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
- src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
- src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
- src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
Closes #232
읽지 않은 알림 뿐만 아니라 전체 알림을 조회 가능하도록 API 추가
읽음 여부와 관계 없이 전체 알림 조회 추가 및 읽음 여부 반환 추가
> [EA3-187]Feature: 알림 전체 조회 엔드포인트 추가 및 읽음 여부 반환 추기

- src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
- src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementSpecification.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
Closes #238 
스터디 연장 반환값 studyId로 변경
> [EA3-191] refactor: 스터디 연장 반환값 변경

- src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/request/RecruitmentPostUpdateRequest.java
> [EA3-190] Refactor: 모집글 수정 필드명 수정

- src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
- src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
- src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyHeaderResponse.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Closes #247 
스터디 헤더 조회 필드 추가
- 스터디 헤더 조회 필드 추가
- 스터디 정보 조회 리더 권한 임시로 해제
> [EA3-196] feature: 스터디 헤더 조회 필드 추가

- src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/response/RecruitmentPostWithStudyInfo.java
- src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
- 닫힌 이슈
- 모집글 조회시 모집글 작성자의 식별자, 이미지 추가
> [EA3-138] feature: 모집글 조회시 모집글 작성자의 식별자, 이미지 추가

- src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Closes #254 
스터디 정보 조회 권한 스터디장으로 수정
> [EA3-197] refactor: 스터디 정보 조회 권한 수정

- src/main/java/grep/neogulcoder/domain/study/repository/StudyQueryRepository.java
Closes #255 
스터디 목록 조회 유저 닉네임 -> 스터디장 닉네임 수정
> [EA3-198] refactor: 스터디 목록 조회 스터디장 닉네임 수정

- src/main/java/grep/neogulcoder/global/auth/oauth/OAuthSuccessHandler.java
OAuth 로그인 후 리다이렉트 Url 수정
OAuth 로그인 후 리다이렉트 Url 수정
> Feature: 배포 후 OAuth 리다이렉트 Url 수정

- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
- src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
- src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
- src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
Closes #270 
스터디 초대 거절 시 해당 알림을 찾지 못하는 오류 수정
잘못된 매개변수로 인해 알림을 찾지 못하였고, 해당 부분 수정
> [EA3-201]Fix: 초대 수락/거절 시 받은 사람 ID와 알림 ID를 통해 찾도록 변경

- src/main/java/grep/neogulcoder/global/config/security/SecurityConfig.java
- 로그인 하지 않아도 모집글 조회 가능 하도록 시큐리티 경로 추가
> [EA3-138] feature: 모집글 조회 시큐리티 설정 추가

- src/main/resources/data.sql
References #228 
chore : data.sql 스터디 멤버 번호 수정(test 계정)
> [EA3-183] chore : data.sql 스터디 멤버 번호 수정(test 계정)

- src/main/java/grep/neogulcoder/domain/review/controller/dto/request/ReviewSaveRequest.java
> [EA3-156] feature: 주관식 리뷰 작성시 빈값 허용 방지 추가

- src/main/java/grep/neogulcoder/domain/admin/controller/AdminController.java
- src/main/java/grep/neogulcoder/domain/admin/controller/AdminSpecification.java
- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
- src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
- src/main/java/grep/neogulcoder/domain/prtemplate/controller/PrTemplateController.java
- src/main/java/grep/neogulcoder/domain/prtemplate/controller/PrTemplateSpecification.java
- src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
- src/main/java/grep/neogulcoder/domain/users/controller/UserSpecification.java
Closes #284 
컨트롤러에서 전달하는 응닶값 변경
회원에 대한 응답값 ResponseEntity로 감싸서 넘기도록 변경
관리자에 대한 응답값 ResponseEntity로 감싸서 넘기도록 변경
알림에 대한 응답값 ResponseEntity로 감싸서 넘기도록 변경
PR 템플릿에 대한 응답값 ResponseEntity로 감싸서 넘기도록 변경
> [EA3-206] Refactor: 응답값에 대한 변경

- src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
- src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
- src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
- src/main/java/grep/neogulcoder/domain/study/provider/InviteMessageProvider.java
- src/main/java/grep/neogulcoder/domain/study/provider/StudyExtendMessageProvider.java
- src/main/java/grep/neogulcoder/domain/study/provider/StudyExtensionReminderMessageProvider.java
- src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationApprovedMessageProvider.java
- src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationMessageProvider.java
- src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationRejectedMessageProvider.java
- src/main/java/grep/neogulcoder/domain/timevote/provider/TimeVoteMessageProvider.java
- src/main/java/grep/neogulcoder/global/provider/finder/MessageFinder.java
Closes #286 
알림 도메인 타입 검증 에러코드 수정
- IllegalArgumentException -> 에러 코드 수정
> [EA3-207] refactor: 알림 도메인 타입 검증 에러코드 수정

- src/main/resources/data.sql
> [EA3-207] fix: sql 알림 타입 수정

- build.gradle
> [EA3-183] chore : JWT 의존성 수정 및 추가

- src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
스터디 초대 시 에러 해결
RequestParam 부재로 인해 값을 읽어오지 못해 에러 발생한 부분 수정
> Fix: 스터디에 초대 시 RequestParam 부재로 인한 에러 해결

- src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
Closes #242 
스터디 종료 로직 쿼리 수정
n+1 문제 해결
> [EA3-195] refactor: 스터디 종료 로직 쿼리 수정

- src/main/java/grep/neogulcoder/domain/recruitment/RecruitmentErrorCode.java
- src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
- src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/request/save/RecruitmentPostCreateRequest.java
- src/main/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostSaveService.java
- src/main/java/grep/neogulcoder/domain/study/Study.java
References #290 
- 모집글 모집 기간 수정
- 모집 기간은 오늘 ~ 스터디 종료 날짜 까지
> [EA3-209] refactor: 모집글 저장시 모집 기간 수정

- src/main/java/grep/neogulcoder/domain/buddy/entity/BuddyEnergy.java
- src/main/java/grep/neogulcoder/domain/buddy/repository/BuddyEnergyRepository.java
- src/main/java/grep/neogulcoder/domain/buddy/service/BuddyEnergyService.java
- src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
- src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberRepository.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
- src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Closes #242 
스터디 종료 로직 수정 및 쿼리 수정
- 스터디 종료 시 버디에너지 증가 로직 수정 (n+1 문제 해결)
- 스터디 멤버 조회 쿼리 수정
> [EA3-195] refactor: 스터디 종료 로직 수정 및 쿼리 수정

- src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
- src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
- 모집글 검색 수정
- 스터디 게시글 수정
- 모집글 검색어 사용시 제목과 내용중 일치 하는 내용이 있다면 검색
---
- 스터디 게시글 검색 결과 최신순 정렬 추가
> [EA3-209] Refactor: 모집글, 스터디 게시글 검색 수정

- src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
- src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyManagementServiceFacade.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyMemberCountService.java
- src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
- src/main/java/grep/neogulcoder/domain/studyapplication/service/ApplicationService.java
Study currentCount 증감 오류 해결
StudyManagementServiceFacade, StudyMemberCountService 스프링 AOP 프록시 적용
> fix: Study currentCount 증감 오류 해결

- src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
- 스터디 게시글 검색 쿼리 수정
- studyPostCommnet.activated.isTrue() where 절이 아닌 on 절로 이동
> refactor: 스터디 게시글 검색 조회 수정

- .github/workflows/create-jira-issue.yml
- .gitignore
- src/main/resources/application-template.properties
Closes #319 
- .gitignore 규칙 업데이트
- application-template.properties 추가
- 이슈 생성시 main 기준 브랜치 생성하도록 변경
- `.gitignore` 규칙 업데이트
- application.properties 무시
- application-local.properties 무시
- application-test.properties 무시
- application-prod.properties 무시
- application-prod-aws.properties 무시 
- application-prod-gcp.properties 무시
- `application-template.properties` 추가
- 로컬/환경 변수 기반 설정 참고용 템플릿 파일
- `create-jira-issue`에 기존 develop 기준 브랜치 생성 되던걸 main 기준 브랜치 생성 되도록 변경
-`application-template.properties`의 경우 한글로 올리면 자꾸 깨져서 영어로 설명을 기입했습니다!
- 따로 application 파일을 추가할 경우 앞으로는 `.gitignore`에 추가 해야합니다!
> [EA3-213] chore: application-template.properties 추가 및 브랜치 생성시 main 기준으로 생성 되도록 변경

- src/main/java/grep/neogulcoder/NeogulCoderApplication.java
- src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
- src/main/java/grep/neogulcoder/domain/users/controller/UserSpecification.java
- src/main/java/grep/neogulcoder/domain/users/controller/dto/request/EmailVerifyRequest.java
- src/main/java/grep/neogulcoder/domain/users/controller/dto/request/SendCodeToEmailRequest.java
- src/main/java/grep/neogulcoder/domain/users/entity/User.java
- src/main/java/grep/neogulcoder/domain/users/exception/MailSendException.java
- src/main/java/grep/neogulcoder/domain/users/exception/MailTaskRejectedException.java
- src/main/java/grep/neogulcoder/domain/users/exception/code/UserErrorCode.java
- src/main/java/grep/neogulcoder/domain/users/service/MailService.java
- src/main/java/grep/neogulcoder/domain/users/service/UserService.java
- src/main/java/grep/neogulcoder/global/config/MailConfig.java
- src/test/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
- src/test/java/grep/neogulcoder/domain/users/service/MailServiceTest.java
- 문제: 메일 전송시 4-5초 시간이 걸림
- 문제 원인: 메일 전송의 완료한 후 응답을 주기 때문에 오랜 시간이 걸림
- 해결 방법: 비동기로 메일 전송을 지시한후 요청 스레드는 바로 응답을 반환
---
- 비동기 스레드풀 관리 하는 객체
- 기본 스레드 5개, 요청이 많은 경우 최대 10개 스레드 생성 ( CorePool, MaxPool )
- 요청이 많은 경우 생성된 스레드는 60초 유지 ( KeepAliveSeconds )
- 서비스 종료시 남은 작업을 수행 할지 여부X ( WaitForTasksToCompleteOnShutdown, awaitTerminationSeconds )
- 큐에 작업이 가득찬 경우 작업을 거부 하고 예외 발생
```java
@Bean
public Executor mailExecutor() {
ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
executor.setQueueCapacity(5);
executor.setCorePoolSize(5);
executor.setMaxPoolSize(10);
executor.setKeepAliveSeconds(60);
executor.setWaitForTasksToCompleteOnShutdown(false);
executor.setAwaitTerminationSeconds(0);
executor.setThreadNamePrefix("MailExecutor-");
executor.setRejectedExecutionHandler((r, e) -> { …
```
> Feature: 메일 전송 비동기 변경
